### ISSUE TITLE
sing-box 1.11的版本好像对 wireguard 协议做了特殊处理，一些建议吧，可能不重要

### ISSUE THREAD

**Issue by 20241204** [Toperlock/sing-box-subscribe#113]
### 描述

当我对 clash 中的 wireguard 协议节点转换的时候，sing-box check 检查生成的 config.json 文件会有警告
比如 clash 原始文件如下
```
proxies:
- ip: 172.16.0.2
  mtu: 1280
  name: 🇳🇱 NL-CF-WARP-1
  port: 8886
  private-key: KEeuUuY+SnmMzlogzyOVH+50jUtjlcro3HyafPHIKHk=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  remote-dns-resolve: true
  server: 188.114.99.244
  type: wireguard
  udp: true
```
转换的节点正常的如下
```
  "outbounds": [
        {
      "tag": "🇳🇱 NL-CF-WARP-1",
      "type": "wireguard",
      "server": "188.114.99.244",
      "server_port": 8886,
      "private_key": "KEeuUuY+SnmMzlogzyOVH+50jUtjlcro3HyafPHIKHk=",
      "peer_public_key": "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=",
      "local_address": [
        "172.16.0.2/32"
      ]
    }
```
当我执行了 sing-box check -c config.json 会有一下警告
```
WARN[0000] legacy wireguard outbound is deprecated in sing-box 1.11.0 and will be removed in sing-box 1.13.0, checkout documentation for migration: https://sing-box.sagernet.org/migration/#migrate-wireguard-outbound-to-endpoint
```
于是我查看了 https://sing-box.sagernet.org/migration/#migrate-wireguard-outbound-to-endpoint 发现已经这个配置废弃了，手动按照官方的建议修改配置为以下的样子才不会有警告
```
 "outbounds": [
    {
      "type": "selector",
      "tag": "Proxy",
      "outbounds": [
        "🇳🇱 NL-CF-WARP-1"
      ]
    }
 ],
  "endpoints": [
    {
      "tag": "🇳🇱 NL-CF-WARP-1",
      "type": "wireguard",
      "private_key": "KEeuUuY+SnmMzlogzyOVH+50jUtjlcro3HyafPHIKHk=",
      "peers": [
        {
          "address": "188.114.99.244",
          "port": 8886,
          "public_key": "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=",
          "allowed_ips": [
            "0.0.0.0/0"
          ]
        }
      ],
      "address": [
        "172.16.0.2/32"
      ]
    }
  ]
```
但是我也不知道这么配置是否正确，毕竟只是警告，我想说的是，可能需要对 parsers/wg.py 脚本做处理，返回的处理结果可能需要放入到 endpoints 节点，然后在 outbounds 中引用，我觉得这很复杂，我没能力修改项目，我甚至都不知道那个调用 parsers/wg.py 的文件在哪，是啊，我很差劲，因为我这只是个警告，所以可能不优化也可以？但是我觉得还是提一嘴比较好，希望你们不会烦我，我的最终文件如下,但是执行的时候还是不太对劲
[singbox-config.json](https://github.com/user-attachments/files/18049073/singbox-config.json)
效果如图
![image](https://github.com/user-attachments/assets/84b21eae-31e5-4bf1-b0f3-9269f05170ac)
控制端似乎无法正常显示，我觉得我的配置可能还是不正常，但是作为改进建议，我觉得应该是有意义的吧，那我就写到这里吧，晚安
![image](https://github.com/user-attachments/assets/68d33598-fe31-4d78-ac2f-5da36ab2fb5e)

### 完整性要求

- [X] 我保证阅读了reademe文档，了解所有sing-box-subscrib使用参数的含义与工作流程。
- [X] 我保证转换的订阅链接可以在浏览器打开，并且有内容。
